=== jacob-sabella/sockbowl-ng/src/app/game/models/sockbowl/questions-models.schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Bonus" : {
      "type" : "object",
      "properties" : {
        "bonusParts" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/HasBonusPart"
          }
        },
        "id" : {
          "type" : "string"
        },
        "preamble" : {
          "type" : "string"
        },
        "subcategory" : {
          "$ref" : "#/$defs/Subcategory"
        }
      }
    },
    "BonusPart" : {
      "type" : "object",
      "properties" : {
        "answer" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "question" : {
          "type" : "string"
        }
      }
    },
    "Category" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      }
    },
    "ContainsBonus" : {
      "type" : "object",
      "properties" : {
        "bonus" : {
          "$ref" : "#/$defs/Bonus"
        },
        "id" : {
          "type" : "integer"
        },
        "order" : {
          "type" : "integer"
        }
      }
    },
    "ContainsTossup" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer"
        },
        "order" : {
          "type" : "integer"
        },
        "tossup" : {
          "$ref" : "#/$defs/Tossup"
        }
      }
    },
    "Difficulty" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      }
    },
    "HasBonusPart" : {
      "type" : "object",
      "properties" : {
        "bonusPart" : {
          "$ref" : "#/$defs/BonusPart"
        },
        "id" : {
          "type" : "integer"
        },
        "order" : {
          "type" : "integer"
        }
      }
    },
    "Subcategory" : {
      "type" : "object",
      "properties" : {
        "category" : {
          "$ref" : "#/$defs/Category"
        },
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        }
      }
    },
    "Tossup" : {
      "type" : "object",
      "properties" : {
        "answer" : {
          "type" : "string"
        },
        "id" : {
          "type" : "string"
        },
        "question" : {
          "type" : "string"
        },
        "subcategory" : {
          "$ref" : "#/$defs/Subcategory"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "bonuses" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/ContainsBonus"
      }
    },
    "difficulty" : {
      "$ref" : "#/$defs/Difficulty"
    },
    "id" : {
      "type" : "string"
    },
    "name" : {
      "type" : "string"
    },
    "tossups" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/ContainsTossup"
      }
    }
  },
  "title" : "Packet"
}

=== jacob-sabella/sockbowl-ng/quicktype/samples/Packet.json
{
  "id": "f3c63c85-3292-48d7-8de2-6053472596f1",
  "name": "2021 SMH \u2014 Packet 3",
  "difficulty": {
    "id": "a6751fbf-d8ad-4cf1-bc7e-a14f87bcddf9",
    "name": "Hard High School"
  },
  "tossups": [
    {
      "order": 0,
      "tossup": {
        "id": "70b8b384-6be2-47ec-9539-910297e8cee0",
        "question": "<b>This author wrote that \"If I were the Head of the Church or the State, / I\u2019d powder my nose and just tell them to wait\" in \"Calypso.\" A poem by this author describes the \u201cenlightenment driven away\u201d and \u201chabit-forming pain\u201d while someone repeats the vow \"I will be true to the wife, / I'll concentrate more on my work.\" The speaker of that poem by this author is \u201cBeleaguered by the same / Negation and despair\u201d and says he is composed (*)</b> \u201cOf Eros and of dust.\u201d This author wrote of a man who \u201cserved the Greater Community\u201d and worked for \u201cFudge Motors Inc\u201d and wonders \u201cWas he free? Was he happy?\u201d \u201cExiled Thucydides\u201d is mentioned in a poem in which this author sits \u201cin one of the dives / On Fifty-second Street.\u201d For 10 points, name this poet of \u201cThe Unknown Citizen\u201d and \u201cSeptember 1, 1939.\u201d",
        "answer": "Wystan Hugh <b><u>Auden</u></b>",
        "subcategory": {
          "id": "28fa8fdf-c6e0-457f-a968-8ea6c8b98c4d",
          "name": "American Literature",
          "category": {
            "id": "a1bf6fee-c23c-4a54-8223-44f1051af84a",
            "name": "Literature"
          }
        }
      }
    },
    {
      "order": 1,
      "tossup": {
        "id": "5585dbc8-d909-4d92-9090-9cedb4169a86",
        "question": "<b>Thinkers from this institution theorized that an \u201cindefinite Dyad (\u201cDIE-add\u201d)\u201d is the sole source of multiplicity from a figure known as \u201cthe One.\u201d A thinker from this institution wrote a text that tries to compare the mind to a birdcage and knowledge to birds; that text partly inspired the thoughts of this institution\u2019s \u201cNew\u201d era. A branch of skepticism named for this institution is contrasted with Pyrrhonian (\u201cpih-ROE-nee-en\u201d) skepticism. One thinker from this institution theorized that learning is simply (*)</b> uncovering innate knowledge from a past existence. A phrase translating to \u201cLet none but geometers enter here\u201d was inscribed at the entrance of this institution.. The Lyceum (\u201clye-KEE-um\u201d) was formed in response to the teachings of this institution. For 10 points, name this school at which Plato taught.",
        "answer": "the <b><u>Academy</u></b> [or the <b><u>Platonic Academy</u></b>; accept the <b><u>New Academy</u></b>; accept the <b><u>academia</u></b>; do NOT accept or prompt on the \u201cSchool of Athens\u201d]",
        "subcategory": {
          "id": "11eda207-38a3-4160-a690-6b0a6df542d4",
          "name": "Philosophy",
          "category": {
            "id": "dc09f9dc-bd37-4bb9-8457-cad7c6c12dba",
            "name": "Philosophy"
          }
        }
      }
    },
    {
      "order": 2,
      "tossup": {
        "id": "f7635e4f-3e99-4a29-98fc-94de2a702bce",
        "question": "<b>Due to raids from the locals, Roman merchants operating in this body of water abandoned Didoros Island in favor of Oreine (\u201coh-RAY-in-ee\u201d). Many Roman merchants lived in the port of Adulis on this body of water, which was under the control of a kingdom ruled by Zoskales. The kingdoms of Saba\u2019 and Himyar exported (*)</b> frankincense and myrrh (\u201cmurr\u201d) to the Roman Empire through this sea, whose western coastline was also home to the kingdom of Axum. One kingdom whose eastern coastline was on this sea was ruled by Hatshepsut, who sent a trading expedition to Punt via this sea. For 10 points, the eastern coast of Egypt is located on what sea that separates the Arabian peninsula from Africa?",
        "answer": "<b><u>Red</u></b> Sea [accept <b><u>Erythrean</u></b> Sea; accept <b><u>Sea</u></b> of <b><u>Reeds</u></b>; accept <b><u>Yam Suf</u></b>; prompt on <u>Indian Ocean</u>]",
        "subcategory": {
          "id": "ce83845c-51e6-4903-9833-935ad09b8ef4",
          "name": "Other History",
          "category": {
            "id": "ebdba259-90ac-4e38-af0f-a61dcefcd16f",
            "name": "History"
          }
        }
      }
    },
    {
      "order": 3,
      "tossup": {
        "id": "e32edb43-4099-4e64-be2c-9c49d4e3573a",
        "question": "<b>A chapter in this book describes how radiation has taken on a shift of meaning from the harmless effects of the Sun to the deadly atomic powers of mankind. This book\u2019s last chapter contains a quote likening science to a river that is \u201cbroadened by\u2026 generalizations\u201d and implores the reader to take the \u201croad less traveled by\u201d instead of the \u201csmooth superhighway.\u201d This book\u2019s first chapter describes a quiet town hit with a \u201cstrange blight\u201d caused by a \u201cwhite granular powder,\u201d and is titled (*)</b> \u201cA Fable for Tomorrow.\u201d The pamphlet A Desolate Year was published by the Monsanto corporation against this book, which explores the effects of biomagnification and coined the term \u201cbiocide.\u201d For 10 points, name this environmentalist book outlining the dangers of DDT by Rachel Carson.",
        "answer": "<b><u>Silent Spring</u></b>",
        "subcategory": {
          "id": "c40a45c2-7b47-41c6-81fc-ebc653469684",
          "name": "Other Academic",
          "category": {
            "id": "0403b947-eb97-40ef-b54c-128469f7c3f2",
            "name": "Other Academic"
          }
        }
      }
    },
    {
      "order": 4,
      "tossup": {
        "id": "2a149196-e854-4859-809c-f06e7fe4be76",
        "question": "<b>One of these devices is split across two circuits in a flyback converter. The current lags behind the voltage by 90 degrees in phasor diagrams for these devices. The impedance in these devices is proportional to frequency, meaning that high-frequency signals cannot pass through them. Devices of this type that block AC but allow DC to pass through are called (*)</b> chokes. The voltage across one of these devices has a linear relationship with the time derivative of current. Transformers are composed of two or more of these devices around a metal ring. These devices are found in RLC circuits along with resistors and capacitors. For 10 points, name these circuit components that store energy in a magnetic field, often using wire coiled around a core.",
        "answer": "<b><u>inductor</u></b>s [prompt on <u>transformer</u>s before mentioned]",
        "subcategory": {
          "id": "057258f6-5630-4623-9331-00789ae9e265",
          "name": "Physics",
          "category": {
            "id": "54faf6a0-fe40-4f9d-a26e-316aee874be5",
            "name": "Science"
          }
        }
      }
    },
    {
      "order": 5,
      "tossup": {
        "id": "f00d9a67-dfb5-47f4-9c06-4254ab907cb7",
        "question": "<b>A purple one of these objects appears on the ground between a pelvis and machinery in Frida Kahlo\u2019s Henry Ford Hospital. In a 1935 painting, a white and yellow one of these things adorns a floating object against brown hills and a cloudy sky. A man on all fours uses a yellow ribbon to strap a heavy basket of these objects to his back in a Diego Rivera painting showing a (*)</b> Carrier of these objects.The interpretation of paintings of these objects like Red Canna as stand-ins for female genitalia was rejected by an artist who created hundreds of paintings of these objects and animal skulls at her New Mexico studio. For 10 points, identify these colorful plant parts painted by Georgia O\u2019Keeffe in works like Black Iris and Red Poppy.",
        "answer": "<b><u>flower</u></b>s [accept oriental <b><u>flower</u></b>s; accept <b><u>lilies</u></b>; accept <b><u>orchid</u></b>s; accept oriental <b><u>poppies</u></b> before mention]",
        "subcategory": {
          "id": "e13f7194-c22b-42c2-b8bd-c4eefb010939",
          "name": "Visual Fine Arts",
          "category": {
            "id": "c71e6d8d-ac9b-4153-b2b4-b7b4586c01fb",
            "name": "Fine Arts"
          }
        }
      }
    },
    {
      "order": 6,
      "tossup": {
        "id": "c6e56531-bfb3-4ebf-a9d7-8d468ab30971",
        "question": "<b>One rebellion against this monarch was partially instigated by his passage of the Statute of Uses. Silken Thomas unsuccessfully attacked Dublin Castle during the Kildare Rebellion against this monarch. A banner with the \u201cFive Wounds of Christ\u201d was used in a rebellion against this monarch. Francis Bigod led a failed rebellion against this monarch after he crushed another uprising led by Robert (*)</b> Aske. The Pilgrimage of Grace emerged against this monarch in response to the dissolution of monasteries spearheaded by this monarch\u2019s minister Thomas Cromwell. That policy was implemented after this monarch established the Church of England to annul his marriage to Catherine of Aragon. For 10 points, name this Tudor monarch famous for his six wives.",
        "answer": "<b><u>Henry VIII</u></b> [prompt on <u>Henry</u> Tudor]",
        "subcategory": {
          "id": "0ff64017-a5af-4a8e-9e16-524a136258ec",
          "name": "European History",
          "category": {
            "id": "ebdba259-90ac-4e38-af0f-a61dcefcd16f",
            "name": "History"
          }
        }
      }
    },
    {
      "order": 7,
      "tossup": {
        "id": "f00277af-90e6-4793-845e-8be935093dce",
